variables:
  VERSION_MAJOR_MINOR: '0.0'

include:
  - project: 'verituity/devops/cicd-templates'
    file: '/util/git-tag.yml'
    ref: v0.4-stable

stages:
  - test
  - release

release:
  stage: release
  extends: .git-tag
  variables:
    GIT_TAG_PREFIX: $VERSION_MAJOR_MINOR
